# Generated by Django 3.1.1 on 2021-01-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubofficialsprofile',
            name='student',
            field=models.BooleanField(default=False, verbose_name='Are you a Student'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='student',
            field=models.BooleanField(default=False, verbose_name='Are you a Student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='noemail', max_length=254),
        ),
    ]
