# Generated by Django 3.1.4 on 2020-12-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
