# Generated by Django 3.1.4 on 2020-12-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201230_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_email_send',
            field=models.BooleanField(default=False),
        ),
    ]
