# Generated by Django 3.1.1 on 2021-01-28 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_clubprofile_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubprofile',
            name='logo',
            field=models.FileField(null=True, upload_to='logo/club/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png'])]),
        ),
    ]
