# Generated by Django 3.1.1 on 2021-03-01 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210301_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubsignings',
            name='created_at',
        ),
    ]
