# Generated by Django 3.1.1 on 2021-01-21 21:46

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210121_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubofficialsprofile',
            name='pincode',
            field=models.CharField(max_length=10, validators=[core.validators.validate_Indian_pincode], verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='clubprofile',
            name='pincode',
            field=models.CharField(max_length=10, validators=[core.validators.validate_Indian_pincode], verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='pincode',
            field=models.CharField(max_length=10, validators=[core.validators.validate_Indian_pincode], verbose_name='Pincode'),
        ),
    ]
