# Generated by Django 3.1.1 on 2021-01-26 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_clubprofile_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.phonenumber'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CLUB', 'Club Account'), ('PLAYER', 'Player'), ('CLUB OFFICIAL', 'Club Secretary/President/Manager'), ('OTHER', 'OTHER')], default='OTHER', max_length=50, verbose_name='User type'),
        ),
    ]
