# Generated by Django 3.1.1 on 2021-01-26 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210127_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubsignings',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubsignings', to='users.clubprofile'),
        ),
        migrations.AlterField(
            model_name='clubsignings',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubsignings', to='users.playerprofile'),
        ),
    ]
