# Generated by Django 3.1.1 on 2021-03-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210301_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerprofile',
            options={'permissions': (('edit', 'Edit'),)},
        ),
        migrations.RemoveField(
            model_name='clubofficialsprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='clubofficialsprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='clubofficialsprofile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
