# Generated by Django 3.1.1 on 2021-03-02 10:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210301_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsignings',
            name='terminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='clubsignings',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='EndContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('accepted', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endcontract', to='users.clubprofile')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endcontract', to='users.playerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
