# Generated by Django 3.1.1 on 2021-03-02 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210302_1547'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='endcontract',
            unique_together={('club', 'player')},
        ),
        migrations.RemoveField(
            model_name='endcontract',
            name='accepted',
        ),
    ]
