# Generated by Django 3.1.1 on 2021-02-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='request_review',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='verified',
        ),
        migrations.AddField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('NEED REVIEW', 'NEED REVIEW'), ('VERIFIED', 'VERIFIED'), ('PENDING', 'PENDING')], default='PENDING', max_length=15),
        ),
    ]
