# Generated by Django 3.1.1 on 2021-02-14 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_auto_20210129_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.PositiveIntegerField(default=0)),
                ('win', models.PositiveIntegerField(default=0)),
                ('draw', models.PositiveIntegerField(default=0)),
                ('loss', models.PositiveIntegerField(default=0)),
                ('goals_for', models.PositiveIntegerField(default=0)),
                ('goals_against', models.PositiveIntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='users.clubprofile')),
            ],
        ),
    ]
