# Generated by Django 3.1.1 on 2021-02-03 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=200, verbose_name='Long name')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='Short name')),
                ('abbr', models.CharField(max_length=10, verbose_name='Abbreviation')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=32, verbose_name='Season')),
                ('cro_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Club Registration Opening Date')),
                ('crc_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Club Registration Closing Date')),
                ('twc_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Transfer Window closing date')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league.league')),
            ],
        ),
    ]
