# Generated by Django 3.1.1 on 2021-02-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='season',
            new_name='name',
        ),
    ]
