# Generated by Django 3.1.1 on 2021-02-03 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20210203_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='crc_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Club Registration Closing Date'),
        ),
        migrations.AlterField(
            model_name='season',
            name='cro_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Club Registration Opening Date'),
        ),
        migrations.AlterField(
            model_name='season',
            name='twc_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transfer Window closing date'),
        ),
    ]
