# Generated by Django 3.1.1 on 2021-01-19 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='clubdetails',
            name='home_ground',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='of_club', to='registration.grounds'),
        ),
    ]
