# Generated by Django 3.1.4 on 2020-12-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='email',
            field=models.EmailField(blank=True, help_text='Email Id', max_length=254, null=True, unique=True),
        ),
    ]
