# Generated by Django 3.1.4 on 2020-12-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20201230_0915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verification',
        ),
    ]
