# Generated by Django 3.1.4 on 2021-01-02 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20210102_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitations',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='registration.officials'),
        ),
    ]
