# Generated by Django 3.1.4 on 2021-01-02 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_invitations_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitations',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='registration.officials'),
        ),
    ]
