# Generated by Django 3.1.4 on 2021-01-03 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0007_auto_20210102_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitations',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='registration.officials'),
        ),
        migrations.AlterField(
            model_name='officials',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Official', to=settings.AUTH_USER_MODEL),
        ),
    ]
