# Generated by Django 3.1.1 on 2021-01-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20210103_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressproof',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ageproof',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jerseypicture',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
