# Generated by Django 3.1.1 on 2021-01-11 13:28

from django.db import migrations
import exiffield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20210110_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressproof',
            name='exif',
            field=exiffield.fields.ExifField(default={}, editable=False),
        ),
        migrations.AddField(
            model_name='ageproof',
            name='exif',
            field=exiffield.fields.ExifField(default={}, editable=False),
        ),
        migrations.AddField(
            model_name='jerseypicture',
            name='exif',
            field=exiffield.fields.ExifField(default={}, editable=False),
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='exif',
            field=exiffield.fields.ExifField(default={}, editable=False),
        ),
    ]
