# Generated by Django 3.1.1 on 2021-01-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20210111_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressproof',
            name='exif',
        ),
        migrations.RemoveField(
            model_name='ageproof',
            name='exif',
        ),
        migrations.RemoveField(
            model_name='jerseypicture',
            name='exif',
        ),
        migrations.RemoveField(
            model_name='profilepicture',
            name='exif',
        ),
    ]
