# Generated by Django 3.1.1 on 2021-01-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20210111_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressproof',
            name='orientation',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ageproof',
            name='orientation',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jerseypicture',
            name='orientation',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='orientation',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
