# Generated by Django 3.1.1 on 2021-01-24 08:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_clubprofile_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20, unique=True, verbose_name='Season')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Match Number')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='users.clubprofile')),
                ('ground', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='users.grounds')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='users.clubprofile')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='fixture.fixture')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('season', 'num'), ('season', 'home', 'away', 'date')},
            },
        ),
    ]
