# Generated by Django 3.1.1 on 2021-02-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='status',
            field=models.CharField(choices=[('DONE', 'DONE'), ('FIXED', 'FIXED'), ('TENTATIVE', 'TENTATIVE')], default='TENTATIVE', max_length=20),
        ),
    ]
