# Generated by Django 3.1.1 on 2021-01-24 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_clubprofile_registered'),
        ('fixture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='num',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Match Number'),
        ),
        migrations.AlterUniqueTogether(
            name='matches',
            unique_together={('season', 'home', 'away', 'num')},
        ),
    ]
