# Generated by Django 3.1.1 on 2021-01-24 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_clubprofile_registered'),
        ('fixture', '0002_auto_20210124_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='users.clubprofile'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='ground',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='users.grounds'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='users.clubprofile'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='fixture.fixture'),
        ),
    ]
