# Generated by Django 3.1.1 on 2021-02-07 10:09

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0002_matches_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='matches',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='matches',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('fixed', 'fixed'), ('tentative', 'tentative'), ('canceled', 'canceled')], default='tentative', max_length=20),
        ),
    ]
