# Generated by Django 3.1.1 on 2021-02-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0003_auto_20210207_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='matches',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('fixed', 'fixed'), ('tentative', 'tentative'), ('canceled', 'canceled'), ('postponed', 'postponed')], default='tentative', max_length=20),
        ),
    ]
