# Generated by Django 3.1.1 on 2021-01-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='public/carousel_images/')),
                ('caption_head', models.CharField(blank=True, max_length=100)),
                ('caption_label', models.CharField(blank=True, max_length=300)),
                ('caption_color', models.CharField(choices=[('dark', 'dark'), ('light', 'light')], default='white', max_length=20)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
