# Generated by Django 3.1.1 on 2021-01-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
