# Generated by Django 3.1.1 on 2021-01-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_carouselitem_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='caption_color',
            field=models.CharField(choices=[('dark', 'dark'), ('light', 'light')], default='dark', max_length=20),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='public/carousel_images/'),
        ),
    ]
