# Generated by Django 3.1.1 on 2021-01-22 12:27

import core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('security_code', models.CharField(max_length=120, verbose_name='Security Code')),
                ('phone_number', models.CharField(max_length=10, validators=[core.validators.validate_phone_number], verbose_name='Phone Number')),
                ('session_token', models.CharField(max_length=500, verbose_name='Device Session Token')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Security Code Verified')),
            ],
            options={
                'verbose_name': 'SMS Verification',
                'verbose_name_plural': 'SMS Verifications',
                'db_table': 'sms_verification',
                'ordering': ('-modified_at',),
                'unique_together': {('security_code', 'phone_number', 'session_token')},
            },
        ),
    ]
