# Generated by Django 3.1.1 on 2021-01-25 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_verification', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMSVerification',
        ),
    ]
