# Generated by Django 3.1.1 on 2021-02-04 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20210129_0456'),
        ('fixture', '0002_matches_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PARENT', 'PARENT'), ('FIRST', 'FIRST'), ('BENCH', 'BENCH'), ('PLAYING', 'PLAYING'), ('ONBENCH', 'ONBENCH')], default='PARENT', max_length=10)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('released', models.BooleanField(default=False)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.clubprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fixture.matches')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='match.squad')),
                ('players', models.ManyToManyField(related_name='squads', to='users.PlayerProfile')),
            ],
            options={
                'unique_together': {('club', 'match')},
            },
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='match.squad')),
                ('sub_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_ins', to='users.playerprofile')),
                ('sub_out', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_outs', to='users.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MatchTimeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_half_start', models.DateTimeField(null=True)),
                ('first_half_end', models.DateTimeField(null=True)),
                ('second_half_start', models.DateTimeField(null=True)),
                ('second_half_end', models.DateTimeField(null=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='fixture.matches')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('matchtimeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='match.matchtimeline')),
            ],
        ),
    ]
