# Generated by Django 3.1.1 on 2021-02-07 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fixture', '0003_auto_20210207_1539'),
        ('users', '0005_auto_20210129_0456'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoalAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('pre', 'pre'), ('finalized', 'finalized'), ('approved', 'approved')], default='pre', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ftime', models.IntegerField(default=-1)),
                ('stime', models.IntegerField(default=-1)),
                ('kind', models.CharField(choices=[('parent', 'parent'), ('first', 'first'), ('bench', 'bench'), ('playing', 'playing'), ('onbench', 'onbench'), ('avail', 'avail'), ('suspen', 'suspen')], default='parent', max_length=10)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.clubprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='squad', to='fixture.matches')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='match.squad')),
                ('players', models.ManyToManyField(related_name='squads', to='users.PlayerProfile')),
            ],
            options={
                'unique_together': {('club', 'match')},
            },
        ),
        migrations.CreateModel(
            name='SubstitutionReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuspensionReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'pending'), ('completed', 'completed'), ('canceled', 'canceled')], default='pending', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.playerprofile')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='match.suspensionreason')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('submitted', 'submitted'), ('finalized', 'finalized'), ('approved', 'approved')], default='submitted', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ftime', models.IntegerField(default=-1)),
                ('stime', models.IntegerField(default=-1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='match.substitutionreason')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='match.squad')),
                ('sub_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_ins', to='users.playerprofile')),
                ('sub_out', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_outs', to='users.playerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchTimeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20)),
                ('first_half_start', models.DateTimeField(null=True)),
                ('second_half_start', models.DateTimeField(null=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='fixture.matches')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('submitted', 'submitted'), ('finalized', 'finalized'), ('approved', 'approved')], default='submitted', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('ftime', models.IntegerField(default=-1)),
                ('stime', models.IntegerField(default=-1)),
                ('own', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('attr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='match.goalattr')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='users.clubprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='fixture.matches')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='users.playerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField()),
                ('event_id', models.IntegerField()),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('matchtimeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='match.matchtimeline')),
            ],
            options={
                'ordering': ['event_id'],
            },
        ),
        migrations.CreateModel(
            name='AccumulatedCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('yellow', models.PositiveIntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.playerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('kickoff', 'Kickoff'), ('half_time', 'Half Time'), ('second_half', 'Second Half'), ('final_time', 'Final Time')], default='kickoff', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ftime', models.IntegerField(default=-1)),
                ('stime', models.IntegerField(default=-1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeevents', to='fixture.matches')),
            ],
            options={
                'unique_together': {('match', 'status')},
            },
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('active', 'active'), ('inactive', 'inactive'), ('approved', 'approved')], default='active', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('is_removed', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ftime', models.IntegerField(default=-1)),
                ('stime', models.IntegerField(default=-1)),
                ('color', models.CharField(choices=[('red', 'red'), ('yellow', 'yellow')], default='yellow', max_length=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixture.matches')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.playerprofile')),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='match.cardreason')),
            ],
            options={
                'unique_together': {('player', 'match')},
            },
        ),
    ]
