# Generated by Django 3.1.1 on 2021-02-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='NU19S',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='squad',
            name='NU21S',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='squad',
            name='nU19',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='squad',
            name='nU21',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
