# Generated by Django 3.1.1 on 2021-02-11 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210129_0456'),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='squads', to='users.clubprofile'),
        ),
    ]
