# Generated by Django 3.1.1 on 2021-02-04 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20210204_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
