# Generated by Django 3.1.1 on 2021-02-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20210211_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeevents',
            name='sublabel',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
