# Generated by Django 3.1.1 on 2021-02-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20210208_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='kind',
            field=models.CharField(choices=[('parent', 'Parent'), ('first', 'First Team'), ('bench', 'Sub'), ('playing', 'Playing'), ('onbench', 'Sub'), ('avail', 'Available'), ('suspen', 'Suspended')], default='parent', max_length=10),
        ),
    ]
