# Generated by Django 3.1.1 on 2021-02-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20210204_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='released',
        ),
        migrations.AddField(
            model_name='squad',
            name='timeline',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
