# Generated by Django 3.1.1 on 2021-02-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_timeevents_sublabel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-ftime', '-stime']},
        ),
    ]
