# Generated by Django 3.1.1 on 2021-02-13 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20210212_1919'),
        ('match', '0004_auto_20210212_1900'),
    ]

    operations = [
    ]
