# Generated by Django 3.1.1 on 2021-02-13 21:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0004_auto_20210212_1315'),
        ('users', '0005_auto_20210129_0456'),
        ('match', '0004_auto_20210212_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='against',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards_against', to='users.clubprofile'),
        ),
        migrations.AddField(
            model_name='goal',
            name='against',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goals_against', to='users.clubprofile'),
        ),
        migrations.AddField(
            model_name='squad',
            name='against',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='squads_against', to='users.clubprofile'),
        ),
        migrations.AddField(
            model_name='substitution',
            name='against',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subs_against', to='users.clubprofile'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='users.clubprofile'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('not_done', 'not_done'), ('result', 'result'), ('draw', 'draw')], default='not_done', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('draws', models.ManyToManyField(related_name='draws', to='users.ClubProfile')),
                ('loser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='losses', to='users.clubprofile')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='fixture.matches')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wins', to='users.clubprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
