# Generated by Django 3.1.1 on 2021-02-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_squad_num_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchtimeline',
            name='final_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchtimeline',
            name='half_time',
            field=models.BooleanField(default=False),
        ),
    ]
