# Generated by Django 3.1.1 on 2021-02-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20210204_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='release',
            field=models.BooleanField(default=False),
        ),
    ]
