# Generated by Django 3.1.1 on 2021-02-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_auto_20210208_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event_type',
            new_name='content_type',
        ),
    ]
