# Generated by Django 3.1.1 on 2021-02-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210129_0456'),
        ('fixture', '0004_auto_20210212_1315'),
        ('match', '0005_auto_20210214_0246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-ftime', '-stime', '-pk']},
        ),
        migrations.AddField(
            model_name='suspension',
            name='completed_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fixture.matches'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='users.playerprofile'),
        ),
        migrations.AlterField(
            model_name='suspension',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.playerprofile'),
        ),
    ]
