# Generated by Django 3.1.1 on 2021-02-04 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_squad_release'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squad',
            old_name='release',
            new_name='lock',
        ),
    ]
