# Generated by Django 3.1.1 on 2021-02-04 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_auto_20210205_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='timeline',
        ),
    ]
