# Generated by Django 3.1.1 on 2021-02-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_auto_20210209_2203'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cards',
            unique_together=set(),
        ),
    ]
