# Generated by Django 3.1.1 on 2021-02-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_auto_20210209_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={},
        ),
        migrations.AlterField(
            model_name='squad',
            name='kind',
            field=models.CharField(choices=[('parent', 'Parent'), ('first', 'First Team'), ('bench', 'Sub'), ('playing', 'Playing'), ('onbench', 'On bench'), ('tobench', 'To bench'), ('avail', 'Available'), ('suspen', 'Suspended')], default='parent', max_length=10),
        ),
    ]
