# Generated by Django 3.1.1 on 2021-02-06 11:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import match.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0002_matches_status'),
        ('users', '0005_auto_20210129_0456'),
        ('match', '0007_remove_squad_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoalAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubstitutionReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuspensionReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='squad',
            old_name='updated_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='events',
            name='message',
        ),
        migrations.RemoveField(
            model_name='squad',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='squad',
            name='lock',
        ),
        migrations.AddField(
            model_name='accumulatedcards',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='accumulatedcards',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='cards',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='cards',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='cards',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='submitted', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='cards',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
        migrations.AddField(
            model_name='events',
            name='kind',
            field=models.CharField(choices=[('sub', 'sub'), ('yellowcard', 'yellowcard'), ('redcard', 'redcard'), ('lineup', 'lineup'), ('goal', 'goal'), ('other', 'other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='events',
            name='label',
            field=models.CharField(default='nolabel', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='side',
            field=models.CharField(choices=[('neutral', 'neutral'), ('home', 'home'), ('away', 'away')], default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='events',
            name='sublabel',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='matchtimeline',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='matchtimeline',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='matchtimeline',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='matchtimeline',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
        migrations.AddField(
            model_name='squad',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='squad',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='squad',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='pre', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='squad',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
        migrations.AddField(
            model_name='suspension',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='suspension',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='pending', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='suspension',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('yellow', 'yellow')], default='yellow', max_length=10),
        ),
        migrations.AlterField(
            model_name='squad',
            name='kind',
            field=models.CharField(choices=[('PARENT', 'PARENT'), ('first', 'first'), ('bench', 'bench'), ('playing', 'playing'), ('onbench', 'onbench'), ('avail', 'avail'), ('suspen', 'suspen')], default='PARENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='suspension',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterUniqueTogether(
            name='cards',
            unique_together={('player', 'match')},
        ),
        migrations.AlterUniqueTogether(
            name='suspension',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('submitted', 'submitted'), ('approved', 'approved')], default='submitted', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('own', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('attr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='match.goalattr')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='users.clubprofile')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='fixture.matches')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='users.playerprofile')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, match.models.EventMixin),
        ),
        migrations.RemoveField(
            model_name='suspension',
            name='active',
        ),
        migrations.RemoveField(
            model_name='suspension',
            name='note',
        ),
        migrations.RemoveField(
            model_name='suspension',
            name='updated',
        ),
        migrations.AddField(
            model_name='cards',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='match.cardreason'),
        ),
        migrations.AddField(
            model_name='substitution',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='match.substitutionreason'),
        ),
        migrations.AlterField(
            model_name='suspension',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='match.suspensionreason'),
        ),
    ]
