# Generated by Django 3.1.1 on 2021-02-19 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_auto_20210218_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='attr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='match.goalattr'),
        ),
    ]
