# Generated by Django 3.1.1 on 2021-02-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_auto_20210209_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['ftime', 'stime']},
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_id',
        ),
        migrations.AddField(
            model_name='events',
            name='ftime',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='events',
            name='stime',
            field=models.IntegerField(default=-1),
        ),
    ]
