# Generated by Django 3.1.1 on 2021-02-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_auto_20210206_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='time_label',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='squad',
            name='kind',
            field=models.CharField(choices=[('parent', 'parent'), ('first', 'first'), ('bench', 'bench'), ('playing', 'playing'), ('onbench', 'onbench'), ('avail', 'avail'), ('suspen', 'suspen')], default='parent', max_length=10),
        ),
    ]
