# Generated by Django 3.1.1 on 2021-02-28 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0010_auto_20210227_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='suspension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='match.suspension'),
        ),
        migrations.DeleteModel(
            name='AccumulatedCards',
        ),
    ]
