# Generated by Django 3.1.1 on 2021-03-09 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_auto_20210228_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitution',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='match.substitutionreason'),
        ),
    ]
