# Generated by Django 3.1.1 on 2021-03-13 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0012_auto_20210309_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchtimeline',
            name='final_time',
        ),
        migrations.RemoveField(
            model_name='matchtimeline',
            name='first_half_start',
        ),
        migrations.RemoveField(
            model_name='matchtimeline',
            name='half_time',
        ),
        migrations.RemoveField(
            model_name='matchtimeline',
            name='second_half_start',
        ),
    ]
