# Generated by Django 3.1.1 on 2021-03-16 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0013_auto_20210313_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='red',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yellows', to='match.cards'),
        ),
        migrations.AddField(
            model_name='cards',
            name='removed_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='red_card', to='match.squad'),
        ),
    ]
