# Generated by Django 3.1.1 on 2021-03-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0014_auto_20210317_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='removed_from',
        ),
        migrations.AlterField(
            model_name='squad',
            name='kind',
            field=models.CharField(choices=[('parent', 'Parent'), ('first', 'First Team'), ('bench', 'Sub'), ('playing', 'Playing'), ('onbench', 'On bench'), ('played', 'Played'), ('avail', 'Available'), ('suspen', 'Suspended')], default='parent', max_length=10),
        ),
    ]
